name: Switch
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Switch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
            git submodule init
            git submodule update
      - name: Build Chiaki
        run: scripts/switch/run-docker-build-chiaki.sh
      - name: Upload chiaki.nro
        uses: actions/upload-artifact@v1
        with:
          name: chiaki.nro
          path: ./build_switch/switch/chiaki.nro
